### ISSUE TITLE
Shepherds writeup form should react better when someone provides something besides plain text

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1477]
`type_defect`   |    by rjsparks@nostrum.com

___

See https://datatracker.ietf.org/doc/draft-ietf-rtcweb-data-protocol/shepherdwriteup/, or if it's changed by when you look, check out the history entry made when the writeup was provided on Jul 8, 2014.

___
_Issue migrated from trac:1477 at 2022-03-04 03:50:37 +0000_

**Comment by rjsparks** [comment]
This could become better policed with a mime/magic check, bleach, and maybe just forcing it to be markdown

**Comment by richsalz** [comment]
I think it's a bit early to force a move to markdown; it needs some socialization first.  Or maybe we could pull WGchairs list as I could be wrong.

**Comment by cabo** [comment]
> I think it's a bit early to force a move to markdown; it needs some socialization first. Or maybe we could pull WGchairs list as I could be wrong.

"The future is already there, it is just unevenly distributed"

I think some corners of the IETF would be quite happy, and others would be "what's markdown?"

**Comment by rjsparks** [comment]
Plaintext is markdown and plaintext is all that this ever accepted before.

**Comment by ajeanmahoney** [comment]
This issue was originally caused by an RTF file that was uploaded for the shepherd writeup (seen in a 2014-07-08 entry of the [doc history](https://datatracker.ietf.org/doc/draft-ietf-rtcweb-data-protocol/history/)). If one tries to do that now, the datatracker responds with the following error:

> Uploaded file does not appear to be a text file. Permitted MIME types are text/plain, text/markdown, text/x-rst, text/x-markdown, this file is text/rtf; charset=us-ascii
> Or upload a .txt file.

When markdown is submitted within the form, it's not interpreted as markdown, but it doesn't break anything either. 

I think this issue can be closed.
