### ISSUE TITLE
It should be easy to put documents on session agendas from search results

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#1909]
`keyword_sprint` `type_enhancement`   |    by rjsparks@nostrum.com

___

Chairs should be able to put a document on an upcoming session agenda from within the search results tables as easily as they can add them to their personal community list

___
_Issue migrated from trac:1909 at 2022-03-04 04:54:16 +0000_

**Comment by ajeanmahoney** [comment]
Small clarification: this feature enhancement is a request for the ability to add a document that is retrieved from the results of the main search page to a WG session agenda. A chair can already add documents to an existing session easily from the session's materials page (e.g., https://dt-main.dev.ietf.org/meeting/121/session/stir) (which seems like a more common use case rather than starting from the main search page).

**Comment by rjsparks** [comment]
Yeah - I think this may have been obviated by improvements on the session materials management page. Will close as wontfix
