### ISSUE TITLE
virtual interim meeting agenda pages and links

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#3088]
`type_enhancement`   |    by mcr@sandelman.ca

___

Subject: virtual interim meeting agenda pages and links

I appreciate having the webex and codimd links on the meeting materials page.
But the active region for the link is just too small, and most of us who are
older than 16 can't even notice the active pop.  Please write out the entire
link, not just the icon.

I would like to have the webex and codimd links on the AGENDA page.
All spelt out.

There has been some call for agenda building tools.
I don't object to that, but I feel that it's really lazy chairs that can't
get it right.  Chairs should be encouraged to use markdown format.
The agenda needs to have the webex and codimd and jabber links in the agenda,
so that the agenda page such as:
 https://www.ietf.org/proceedings/interim-2020-drip-06/agenda/agenda-interim-2020-drip-06-sessa-00
are complete.

It's unclear to me why some meetings have agenda links in the IETF Interim
Meeting calendar and many do not.   It could be that Google just never
updates the entry after the agenda link is added closer to the meeting
itself.  Or maybe I'm confused, and virtual interim never got the link?
Google certainly removes the entry quite fast after the meeting has occured.

I'm unclear if we have a version-agnostic link for the agenda, as I see
versioned and unversioned links, and I'd like to make sure that
version-agnostic, last version posted link, is more prominently used.
Could that link go into the calendar entry when the meeting is created, even
if there is no agenda (just leads to 404) yet.

___
_Issue migrated from trac:3088 at 2022-03-04 08:01:35 +0000_

**Comment by rjsparks** [comment]
> I appreciate having the webex and codimd links on the meeting materials page.
But the active region for the link is just too small, and most of us who are
older than 16 can't even notice the active pop. Please write out the entire
link, not just the icon.

This was done on the materials page for each session a few releases ago.

> I'm unclear if we have a version-agnostic link for the agenda,
We do, and it's used where it makes sense to do so.

I think the rest of this issue is OBE, or at least needs the conversation restarted given the changes in the way meetings happen since the original. If you (@mcr) think there's more to pull out of here, please open new issues, each with a specific focus.
