### ISSUE TITLE
Documents page for PPM

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#3668]
### What happened?

https://datatracker.ietf.org/wg/ppm/documents/ doesn't show any documents, however, shouldn't https://datatracker.ietf.org/doc/draft-gpew-priv-ppm/ be a match?

### What browser(s) are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
It wouldn't automatically be a match - the code that automatically matches only looks for the group acronym in the third element (as separated by spaces): draft-whatever-`here`-whatever.

That is, it would have automatically appeared in the related documents section if it had been named draft-gpew-ppm-priv instead of draft-gpew-priv-ppm.

The ppm chairs can add the draft to the page explicitly using the `Manage document list` button.

**Comment by rjsparks** [comment]
I've sent a note to the ppm chairs.
