### ISSUE TITLE
Submission format statistics are missing on the bs5 branch

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#3694]
### What happened?

Not sure if this is case for all development environment runs, but when I try to see statistics of the submitted formats on the development datatracker version using bs5 branch I get all zeros. Most likely it is using some place to collect the data which is not available to the development datatracker, but it would be good to verify that this is really the case, or whether bs5 update broke something.

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
This is a consequence of what filesystem artifacts are provided in the development containers. The view relies on scanning the contents of the draft archive, and that's not provided by default. See https://github.com/ietf-tools/datatracker/discussions/3708.

There's no regression here for bs5. ietf/stats/views.py is identical in main and feat/bs5.

This view, however, is not sane (and will timeout in production if not cached because its computation is quite expensive). As mentioned in #3693 the stats module needs to be rethought.
