### ISSUE TITLE
Feature Request: Allow sending history comments to the WG.

### ISSUE THREAD

**Issue by wkumari** [ietf-tools/datatracker#3885]
### What happened?

DT allows adding a comment / history - e.g: https://datatracker.ietf.org/doc/draft-ietf-dnsop-avoid-fragmentation/edit/addcomment/

It would be nice if there were a "Send this comment to the WG too"; having the history update without being able to tell the WG is helpful.

### What browser(s) are you seeing the problem on?

Not Applicable

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
I think there's missing negation above?

Is there a need for an option to send to the WG or not, or if there's a working group associated with the document, should the comment just always be sent there?

If the latter, this is just a matter of updating the list at
https://datatracker.ietf.org/mailtrigger/name/doc_added_comment/

**Comment by rjsparks** [comment]
I think having an AD say "make this happen" is sufficient. I see no harm in adding the group, as the information is already available to them anyhow. If there turns out to be pushback, we can add the extra complexity for making it an option later.
I'll make the change to the mailtrigger now. It is easy to change back if we need to.

**Comment by rjsparks** [comment]
done (see https://datatracker.ietf.org/mailtrigger/name/doc_added_comment/). Closing this. Reopen if needed.
