### ISSUE TITLE
CI tests fail for test_send_error_to_admins

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3924]
### What happened?

https://github.com/ietf-tools/datatracker/runs/6271450651?check_suite_focus=true#step:6:21

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by jennifer-richards** [comment]
The error occurs because a file name that must appear in an email is split across lines. This happens when the pathname the wrong long length. It's not new to the code - I've seen it on my dev machine under some circumstances. Something about the CI test environment has changed and begun triggering it, though.
