### ISSUE TITLE
UTF8 issue with "send notices to"

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#3938]
### What happened?

See the "Send notices to" line on https://datatracker.ietf.org/doc/draft-ietf-opsec-ipv6-eh-filtering/, which has
```
=?utf-8?q?=C3=89ric_Vyncke?= <evyncke@cisco.com>
```

### What browser(s) are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow the IETF's Code of Conduct

**Comment by rjsparks** [comment]
It's a free-form text field in the datatracker. Somebody pasted that set of bits into the field.
```
>>> Document.objects.get(name='draft-ietf-opsec-ipv6-eh-filtering').notify
'=?utf-8?q?=C3=89ric_Vyncke?= <evyncke@cisco.com>'
```
We could possibly change the field to be a bit more aggressive with validation, but to really pull that off it would probably need to be rethought as a list of email addresses rather than a freeform string.

**Comment by rjsparks** [comment]
maybe - but I can envision, say, a liaising sdo address being used. Parsing the full set of what we have and seeing what _isn't_ in an Email object already would be informative.

**Comment by evyncke** [comment]
My uppercase first name is always a nice test... ;-)

**Comment by rjsparks** [comment]
Bump?

**Comment by larseggert** [comment]
I think this can be closed?
