### ISSUE TITLE
EMODIR reviewers can't change settings

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#3983]
### Describe the issue

When I look at my personal page and go to the reviews profile, I see that I am in secdir artart and emodir.  If I click "change settings" on emodir, the URL is broken: https://datatracker.ietf.org/dir/emodir/reviewers/rsalz@akamai.com/settings/?next=/accounts/review/

Not a big deal; I wasn't aware EMODIR had reviews :)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Emodir is not a review team - it is an error to show it in the reviews profile in the first place.

Internally: emodir is of type `dir`, not type `review` and the distinction between the types is whether the group does reviews.

This is component ietfauth since the bug is at the view associated with /accounts/review

**Comment by kesara** [comment]
Looks like this issue is OBE.
