### ISSUE TITLE
The session requests page needs to show non wg/rg requests

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#3986]
We are now using Sessions to model meetings of many group types other than rg/wg. These sessions should show on the /meeting/requests page.

**Comment by flynnliz** [comment]
(In case this isn't already obvious) I don't think *all* other types of sessions should show on /meeting/requests -- particularly now that there are so many "Secretariat" group sessions for breaks, etc. I'm happy to help look at the options and determine which other kinds of groups/sessions should show on the page if that would be helpful.

**Comment by rjsparks** [comment]
I think groupfeatures.has_meetings is probably a good first cut at what group types to include.

**Comment by jennifer-richards** [comment]
Using `has_meetings` as a filter adds in tdd, but also picks up the ietf and secretariat groups. As @flynnliz anticipated, this results in dozens of entries for the secretariat group and several for the ietf group. This happens because both ietf and secretariat groups are of type "ietf" for which `has_meetings=True`.

The other type "ietf" groups are iesg and iab. For 113, there were no sessions for the iab group. The iesg group had 5 office hours sessions.

We could hide these by changing the `has_meetings` flag to False for "ietf" type groups, though I am not sure what other effects that would have. If we don't want to do that, we will need to explore other criteria for hiding sessions on the page. Suggestions?
