### ISSUE TITLE
EMODIR can't request an interim session

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4004]
While it is listed under `request a session` it is not listed for the _chairs_ at /meeting/interim/request. (It is listed for the secretariat).

**Comment by jennifer-richards** [comment]
There's some weirdness here. If I access as an emodir chair without other group roles, the /meeting/interim/request page does not come up at all. Instead, there's an access denied because the user fails the `can_manage_some_groups()` check.

If I access that view while logged in as an emodir chair who has other group management roles, I see what you describe: the request page comes up and lists the expected groups (other than emodir).

I happened to test using the first case first, so fixed that by adding a role check for "Directorate Chair" that grants access to the /meeting/interim/request page to chairs of directorate groups. That has the unexpected effect of allowing the user to request a session for *any* group at all. I traced this to a mismatch between the modified authorization check and the assumptions in [`set_group_options()` for the interim request form](https://github.com/ietf-tools/datatracker/blob/25c7c4801a0d971f30027d7e1ac21120cefeb242/ietf/meeting/forms.py#L189). That method builds up the set of options based on roles held by the user and implicitly assumes that its cases cover all the roles that could lead to a user having access to the form. If that is not true, then the group list is filtered by an empty `Q()`, which lets all the groups through!

My plan is to fix that form issue - there shouldn't be a path that results in the unfiltered ability to request sessions - and to give Directorate Chairs access to the page.
