### ISSUE TITLE
Items in Upcoming Meetings calendar aren't all listed above the calendar

### ISSUE THREAD

**Issue by agmalis** [ietf-tools/datatracker#4058]
### Describe the issue

On page https://datatracker.ietf.org/meeting/upcoming , not all of the items in the calendar are in the list above the calendar. For example, on June 21, there is a rtgwg interim meeting shown at 15:00-17:00 UTC. However, that meeting isn't included in the list of meetings above the calendar; that list jumps over that meeting as follows (this is copied from the page):

2022-06-16 16:00-18:00 | scitt | interim-2022-scitt-01 |  
2022-06-22 14:00-15:30 | core | interim-2022-core-09 |  

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi Andy - 

Apologies for the delayed response - I think you hit an interesting edge condition since this particular meeting was announced (and would have started showing on the upcoming page) at 11:13 Pacific time, just before this report. 

I suspect it showed up in both places shortly after (and it shows now).

We'll inspect the code to see if there's something that would cause a difference of behavior between the table and the calendar when the meeting session was only very recently announced.

**Comment by agmalis** [comment]
Robert, thanks again for checking.

**Comment by agmalis** [comment]
Robert,

Thanks for the update.

Cheers,
Andy

**Comment by larseggert** [comment]
Close?
