### ISSUE TITLE
New agenda does not work on all browsers

### ISSUE THREAD

**Issue by kivinen** [ietf-tools/datatracker#4246]
### Describe the issue

When using for example seamonkey I get following errors on the javascript console:

JQMIGRATE: Migrate is installed with logging active, version 3.4.0
jquery-migrate-npm-3.4.0-88c209e61f-7431:103:16
SyntaxError: expected expression, got keyword 'import'
agenda.41e6a9da.js:338:22631

and then I get spinning busy marker in the middle of page for ever.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by NGPixel** [comment]
Seems to be a SeaMonkey specific issue. I couldn't replicate on Chrome, Edge, Firefox and Safari browsers.

[Dynamic Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) is supported on over [95% of global browsers usage](https://caniuse.com/es6-module-dynamic-import), and should be supported since Firefox 67.

**Comment by rjsparks** [comment]
See #4247 and https://mailarchive.ietf.org/arch/msg/tools-discuss/0yDvb4WnW8UitkMONkdhnTpVGCY.
