### ISSUE TITLE
Secretariat could not cancel TDD

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4272]
The UI didn't give Liz the ability to cancel TDD at 114.
I added a SchedulingEvent manually through the admin.

**Comment by rjsparks** [comment]
cc @flynnliz

**Comment by jennifer-richards** [comment]
Looks like the edit/cancel buttons are disabled when session requests are closed. Should I open both of those for the secretariat?

**Comment by flynnliz** [comment]
@jennifer-richards I think I'm a little confused. Are we talking about canceling a session _request_ or canceling a session?

Secretariat should definitely be able to cancel/edit a session request while the tool is closed. But canceling a session request from /sreq disappears the session from the agenda completely, which is not always what we want. The issue with TDD is that it doesn't appear on the page where I normally cancel regular sessions (https://datatracker.ietf.org/secr/meetings/115/finalagenda/regularsessions/) -- pushing the Cancel button here flags the session as "cancelled" on the agenda, which is what we want. So the fix needed is not with the request tool but somewhere else that would allow me to trigger the "Canceled" flag on the agenda for a non-regular-WG session.

**Comment by flynnliz** [comment]
(There is a similar button marked cancel for TDD on https://datatracker.ietf.org/secr/meetings/115/finalagenda/miscsessions/, but I don't think it actually works and I have been pretending like that whole Misc. Sessions tab doesn't exist because of the new way we're supposed to be adding these events.) I just tried cancelling TDD that way in the sandbox but the meeting agenda isn't loading so I can't tell if that is supposed to work or not.

**Comment by rjsparks** [comment]
Yes, cancelling sessions is different than cancelling sreqs.
sandbox will be fixed shortly.

**Comment by jennifer-richards** [comment]
I see, I'd gone down the wrong path. I'll detach that PR and deal with this separately

**Comment by jennifer-richards** [comment]
Fixed on the feat/tzaware branch.
