### ISSUE TITLE
The agenda editor is not showing dates in meeting time

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4376]
From @flynnliz (split out from #4375):

> Also, that WG Chairs lunch session is actually from 12:15-13:15 but the header on its rectangle lists 13:30-14:30 as it’s trying to fit itself into the rest of that column, which just adds to the confusion of what times those lpwan and idr sessions are.

The dates are currently in UTC

**Comment by jennifer-richards** [comment]
I think this was a side effect of problems hiding timeslots and was also fixed by #4385. Feel free to reopen if I'm mistaken.

Related ticket #4435 captures problems with time zones on the tzaware branch (there, the entire UI was showing things in Pacific time instead of meeting time, so not really the same).
