### ISSUE TITLE
Schedule editor icons need to be more distinct

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4378]
From @flynnliz

The various “person” icons are confusing. It’s hard to know at a glance in the grid which conflicts are “person who must be present” and which are “chair conflict,” and it’s even more confusing that in the session request data box on the bottom right, the “requested by” icon is the same as the chair conflict. Can these three be more distinct from each other? 

![image](https://user-images.githubusercontent.com/10996692/186988300-df1ea711-d765-47eb-9971-e234ba10f4d8.png)

- The “technology overlap” chain icon shows up really faintly and it’s very tiny, so it’s easy to miss. Same with the “key participant overlap” key icon — those two are really difficult to distinguish from each other when they are so small. Can these be made larger or even just changed to something that takes up more vertical space so they’re easier to distinguish?

![image](https://user-images.githubusercontent.com/10996692/186988318-671fa14e-3388-4780-adee-727146811a00.png)

**Comment by larseggert** [comment]
https://icons.getbootstrap.com/ has all the icon choices. Of course we could pull in another icon library, but that seems like overkill. Would colors help, @flynnliz?

**Comment by flynnliz** [comment]
Thanks for the link to the icon library, @larseggert ! I don't think colors would help, since the agenda editor already changes the colors for certain conflicts in the grid. 

I've chosen some new icons that I think will be a little more visually distinct from each other. Can these be changed?

"Persons who must be present" : people-fill
"Session requested by" : person-circle (no change)
"Chair conflict" : circle-fill
"Technology overlap" : link-45deg
"Key Participant Conflict" : star

**Comment by larseggert** [comment]
@flynnliz like this?
<img width="353" alt="Screen Shot 2022-09-02 at 12 46 14" src="https://user-images.githubusercontent.com/200328/188112954-f9661af4-33a0-4b94-916b-2f2ec95fa30d.png">
