### ISSUE TITLE
Per-document page: If a document is in AUTH48, add a direct link to the document's AUTH48 page (http://www.rfc...

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/datatracker#443]
`keyword_imported` `keyword_sprint` `resolution_overtaken by events` `type_enhancement`   |    by 

___

If a document is in AUTH48, add a direct link to the document's AUTH48
page (http://www.rfc-editor.org/auth48/rfcNNNN). However, this
requires knowing the to-be-RFC-number, which is not in queue2.xml (but
is in queue2.html).

___
_Issue migrated from trac:443 at 2022-03-04 01:32:42 +0000_

**Comment by rjsparks** [comment]
The IESG would like the link from a document to take the viewer _directly_ to the page that shows the auth48 status for that document. The mapping from the document to the page is in https://www.rfc-editor.org/queue2.xml

The best thing to do is capture this link (for each document) when we get the push from the rfc-editor letting us know the document has changed rfc-editor state.

An alternative if that's problematic is to build a dispatch function that uses (and manages) a cached and parsed version of queue2.xml.

Either way it would be nice if we could get this information in json rather than xml at some point.

**Comment by rjsparks** [comment]
(Added for @alicerusso)

**Comment by richsalz** [comment]
It looked like @larseggert did this as part of commit 8bc7fde027 and this can be closed.

**Comment by jennifer-richards** [comment]
Can you point to what you see in 8bc7fde that addresses this? I'm not seeing it, but there's a lot in there so I might just be missing it.

Was this not addressed by https://github.com/ietf-tools/datatracker/commit/fff927b08510db118777d8379015470113adbc67 ? That was committed before this was re-opened, but I'm not sure what's different in this ticket.

**Comment by rjsparks** [comment]
I think the key thing to verify is the word _directly_ in 

>The IESG would like the link from a document to take the viewer directly to the page that shows the auth48 status for that document. The mapping from the document to the page is in https://www.rfc-editor.org/queue2.xml

**Comment by jennifer-richards** [comment]
If I go to https://datatracker.ietf.org/doc/draft-uberti-rtcweb-rfc8829bis/, which is currently in AUTH48, I see 
<img width="551" alt="image" src="https://github.com/ietf-tools/datatracker/assets/19472766/edcf9e4b-5621-4471-9c68-e886a5c9260b">
at the end. The bottom link, "Auth48 status", leads to https://www.rfc-editor.org/auth48/rfc9429

**Comment by rjsparks** [comment]
then lets close this as OBE.
