### ISSUE TITLE
Datatracker: displaying multiple directorate reviews

### ISSUE THREAD

**Issue by evyncke** [ietf-tools/datatracker#4557]
### Describe the issue

Not critical at all, but I made a mistake by requesting several reviews to the same directorate (the DT did now show the request on the I-D status page immediately).

Now, e.g., https://datatracker.ietf.org/doc/draft-ietf-homenet-front-end-naming-delegation/, the I-D status page shows a button for each request. Same for https://datatracker.ietf.org/doc/ad/%C3%A9ric.vyncke 

Unsure whether the I-D status page should show the request as soon as it is requested... or wait until the review request is assigned...

Showing a single button on the I-D/AD status page per directorate would be nicer.

-éric

PS: could work on this at the next Code Sprint

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
I note that each of the three reviews have been assigned to different people.
The secretaries have the option of withdrawing the assignment for two of them, and you have the option of withdrawing the requests.
If you want me to help put this in a cleaner state, let me know which reviewer you want to remain assigned and I'll go punch the buttons (or am happy to talk the secretaries through it).

**Comment by evyncke** [comment]
Sure that this would be the procedure to purge this weird state.

Thinking twice, what about limiting to a SINGLE review request per directorate ?

**Comment by rjsparks** [comment]
That was considered in early design but not pursued since multiple people may want to request reviews of a team providing different review context/instructions.

Maybe what you'd like is a warning that _you_ have already requested a review of this type from this team for this document?

Also note that unless you're reconfiguring the dnsdir team, telechat and last call reviews are automatically suggested - you do not have to request them - in the workflows for teams that use the autosuggest feature, manual review requests are almost only for early reviews.

**Comment by evyncke** [comment]
Robert, as usual: thank you for the added details and sorry to bug you again and again, this is just a token of my hope to help improving the whole system.

The warning is a good idea indeed. And I will tell the directorate secretaries.

I guess we can close this issue
