### ISSUE TITLE
The position on the new meeting agenda page is not preserved when returning there via "Back" button

### ISSUE THREAD

**Issue by smyslov** [ietf-tools/datatracker#4616]
### Describe the issue

When I scroll down the new meeting agenda page to get to the session I'm interested in, then click any link (e.g. to show session agenda) and then press "Back" browser button to return to the meeting agenda, the position on the meeting agenda page get lost - it is displayed from the very beginning, so that I need to scroll it down again to get to the session I'm interested in.

Not a big deal, but definitely inconvenient.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by NGPixel** [comment]
Because of how the website is currently structured, there's not an easy and consistent way to achieve that.

The agenda and meeting floors pages are essentially running as a modern single page application (SPA). If you click on a meeting room link from the agenda, then press Back, you'll get correctly scrolled back to your previous scroll position.

However, clicking on a meeting materials link exits that SPA and it's not possible to know that you've come back to the page in a way that works consistently across all browsers.

As more sections of the site gets refactored to be part of the SPA, the scroll position will be correctly restored when moving between pages. Until then, I suggest clicking on the "Show meeting materials" button, available on the right of each session. This opens a dialog with the materials without leaving the page or losing your scroll position. You could also open the materials in a new tab.
