### ISSUE TITLE
Not suppressing "duplicate" nominations?

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#4637]
### Description

Someone gets nominated for an AD position by three different people. Apparently only the first nomination email gets sent. Is that correct? It can influence someone's desire to accept or not if they see multiple nominations. (This was reported to me by a nominee this week.) Should they get all nominations? I think so.

If they've already accepted or declined, can we tell the person nominating them when they submit the form? In those cases, it makes sense to *not* send the email.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by richsalz** [comment]
I guess this could be used to swamp people with email.  So maybe if the person has already been nominated, we can do a pop-up that says so, and say "no email will be sent" ?

**Comment by rjsparks** [comment]
I'm not sure what should be changed here.

We don't want to cause someone making a nomination to not follow through - the _nomcom_ should see the number of nominations, and who provided them. But telling the nominator "you're not first", especially before the nomination is sent, doesn't seem like a good message.

Something that begins to approximate a score visible to the nominee also doesn't seem like the right thing to do. If the nomcom wants to share something about how strong the nomination force was with the nominee, the message should be customized and a bit abstracted. "A lot of people nominated you" vs "10 people nominated you" seems more appropriate?

If nominators want to make sure that the nominee knows they nominated them, they should tell them themselves rather than have the datatracker tell them.

**Comment by richsalz** [comment]
> If nominators want to make sure that the nominee knows they nominated them, they should tell them themselves rather than have the datatracker tell them.

Maybe we add that to the display?  But then it gets to the "not the first" issue you raised, which is a good point.

**Comment by richsalz** [comment]
> I'm not sure what should be changed here.

I'm not either, now. Close this as wontfix.
