### ISSUE TITLE
Links to meetecho aren't appearing for some sessions of the ietf group

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4745]
(Probably related to session purpose).
At IETF 115, links for meetecho did not automatically appear for the Newcomers session, IEPG, the wgchairs forum, or the host speaker series.

The secretariat entered alternate online coordinates, which shouldn't have been necessary - it resulted in three buttons suddenly appearing - the manually entered coordinates and the automatically generated coordinates that were not present before. In one case (host speaker series), because things were done at meeting speed, those links were _different_.

wgchairs might be different from the others as it was (I think) created as group emodir (which is right), but the links saying emodir rather than wgchairs caused some consternation.

**Comment by jennifer-richards** [comment]
The decision whether to show the buttons at all is here

https://github.com/ietf-tools/datatracker/blob/61f7984d5c3b98de4d57113c14255eaef9180b7f/client/agenda/AgendaScheduleList.vue#L273

The `showAgenda` flag comes from

https://github.com/ietf-tools/datatracker/blob/61f7984d5c3b98de4d57113c14255eaef9180b7f/ietf/meeting/views.py#L1720-L1723

which is why setting the `remote_instructions` value causes buttons to appear.

The standard buttons come from the `Location` (i.e., room) where the session is being held. The meetecho links are generated using the `UrlResource` with `name=='meetecho'`, which (for all rooms) is `https://meetings.conf.meetecho.com/ietf{meeting.number}/?group={group.acronym}&short={short}&item={order_number}` with the bracketed expressions interpolated.

**Comment by jennifer-richards** [comment]
Question: what exactly tneeds to change here? The simplest thing to do would be to turn on the standard meetecho links for these sessions. Assuming the `Room` data are similar to IETF-115 in the future, that will add video stream, audio stream, and onsite tool links. These will be formatted like 
* Host Speaker Series
    * `https://meetings.conf.meetecho.com/ietf115/?group=ietf&short=&item=3`
* New participants' overview
    * `https://meetings.conf.meetecho.com/ietf115/?group=emodir&short=&item=2`
* IEPG
    * `https://meetings.conf.meetecho.com/ietf115/?group=iepg&short=&item=1`
* WG Chairs Forum
    * `https://meetings.conf.meetecho.com/ietf115/?group=emodir&short=&item=4
These are the values for the "video stream" but the other URLs will be similar. I've made up the item numbers, but the groups are accurate.

Are these ok? It doesn't address the consternation about the wgchairs URL containing emodir, but that could be at least partly addressed by giving the session a short name (which would show up in the URL where there's currently a blank value for the `short` query parameter).

**Comment by rjsparks** [comment]
standard meetecho links is what I think is what we are asking for.
