### ISSUE TITLE
Multiple (duplicate) DocEvents being created on Review Assignment

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#4748]
Look at, e.g., https://datatracker.ietf.org/doc/draft-ietf-sfc-oam-packet/history/
```
>>> DocEvent.objects.filter(desc='Request for Last Call review by ARTART is assigned to Barry Leiba',doc__name='draft-ietf-sfc-oam-packet')
<QuerySet [
<DocEvent: draft-ietf-sfc-oam-packet assigned review request by Barry Leiba at 2022-11-08 01:15:55+00:00>, 
<DocEvent: draft-ietf-sfc-oam-packet assigned review request by Barry Leiba at 2022-11-08 01:15:55+00:00>
]>
```

**Comment by jennifer-richards** [comment]
This reflects that both a `ReviewRequestDocEvent` and a `ReviewAssignmentDocEvent` are created:
```
>>> DocEvent.objects.filter(desc='Request for Last Call review by ARTART is assigned to Barry Leiba', doc__name='draft-ietf-sfc-oam-packet').values_list('pk', flat=True)
<QuerySet [890515, 890514]>
>>> ReviewRequestDocEvent.objects.filter(desc='Request for Last Call review by ARTART is assigned to Barry Leiba', doc__name='draft-ietf-sfc-oam-packet').values_list('pk', flat=True)
<QuerySet [890514]>
>>> ReviewAssignmentDocEvent.objects.filter(desc='Request for Last Call review by ARTART is assigned to Barry Leiba', doc__name='draft-ietf-sfc-oam-packet').values_list('pk', flat=True)
<QuerySet [890515]>
```

I'm not sure what the right thing to do is here. Maybe filter events with identical descriptions out of the history?

**Comment by rjsparks** [comment]
Is having a ReviewRequestDocEvent dropped at the point that a ReviewAssignment is made the right thing to do? I suspect it isn't and it's an artifact of before we explicitly split out ReviewAssignments.

**Comment by rjsparks** [comment]
To be explicit - would any expectations be broken if we deleted the ReviewRequestDocEvents that have "is assigned" in their desc, and change the code to quit making new ones?

**Comment by jennifer-richards** [comment]
Looking at the history, when `ReviewAssignment` was added, the places where `ReviewRequestDocEvent` records were created for assigning and closing review requests were duplicated. This happens in a migraiton (`0010_populate_review_assignments.py`) as well as for new activity.

I'm not finding much that looks like it depends on there being the duplicates, so I think it'd be ok. Checked and there is always a `ReviewAssignmentDocEvent` with the same description within a minute of every `ReviewRequestDocEvent` and vice versa, with one exception:
```
ReviewRequestDocEvent.objects.get(doc__name='draft-ietf-sidr-slurm', time='2018-02-19 08:16:27+00').desc
'Request for Last Call review by OPSDIR is assigned to (None)'
```
Not sure what's up with that one.

I'm a little surprised that I had to allow for a full minute of skew to match up identical events between the two classes, but assuming that level of precision is ok, we can recreate the events we remove if it turns out they were needed.

**Comment by rjsparks** [comment]
My instinct says that one is created when a view with a form in it is first fetched, and the other when the form is submitted. When we locate the code that creates them, we'll know for sure.

**Comment by jennifer-richards** [comment]
That seems plausible, but as you can see in #4913, the code that generates the two types of `DocEvent` are (were) back-to-back in a util method. Could be there's another place they're created, but I haven't found one.

There also seem to be a few (~40) cases of `ReviewAssignmentDocEvent` pairs that are identical, but created ~30 seconds apart. Not sure what's going on there, but my working assumption was somebody clicked twice (perhaps due to a slow server response or other error?)
