### ISSUE TITLE
New-style HTMLization issue for draft-lukianets-open-ethics-transparency-protocol-02

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#4784]
### Describe the issue

As mentioned by @rjsparks in Slack:
> Some weird on the htmlized branch:
At https://sandbox-htmlize.ietf.org/doc/draft-lukianets-open-ethics-transparency-protocol/
Note:
![image](https://user-images.githubusercontent.com/200328/203531453-f87a06dd-2510-47ef-bcf4-1d2a17637df3.png)
vs
![image (1)](https://user-images.githubusercontent.com/200328/203531505-37ddca21-79e5-4809-895a-943be163be9e.png)
(that is legacy view)
but the same thing happens with the newer view
https://datatracker.ietf.org/doc/html/draft-lukianets-open-ethics-transparency-protocol-02 doesn’t munge it that way

@martinthomson any idea? I think this may be due to the very long draft name and your CSS?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by martinthomson** [comment]
This is the result of the layout including two `<div class="xml2rfc">` elements nested inside each other.  Then you have rules like this:

```css
.xml2rfc {
  width: 72ch;
  margin-left: 3ch;
  overflow-x: hidden;
}
```

So what is happening is that the inner `<div>` is rendering just fine, but it is being put inside another `<div>` with the same rules, which pushes it 3ch to the right, then cuts off the three rightmost characters.

I recently landed a change to xml2rfc that will have caused this inner `<div>` to be labelled this way.  That's probably what is going on.  I'm sorry that I didn't consider this outcome.  

I don't use `overflow-x: hidden`, so I maybe wouldn't have noticed this either way.  I should point out that there are lots of drafts that do terrible things with overflowing the 72 column limit, so maybe you should be careful about using that directive.  It might be less disruptive to use 'auto' instead.  Of course, that means that the whole document scrolls left-right if you put the directive on the top-level div; I have generally chosen to put that sort of rule on specific elements (like pre and p) so that only those elements get scrollbars as necessary.  You could also let it overflow.

(Incidentially, the maximum font size here - which I get on my largish screen - is *enormous* to the point of hurting my eyes.  Consider dialing it back a notch.)

**Comment by larseggert** [comment]
Thanks for the analysis! I'll see if I can cook up a fix based on this.

**Comment by rjsparks** [comment]
The primary issue was addressed by 4791, but I would like to second Martin's concern about font size.
On my primary monitor, I get 22pt fonts. Could these be easily capped to be a little smaller?

**Comment by larseggert** [comment]
Paul complained that the max font was too small for him previously. There is a pref setting to cap the max font size. Should I make the default smaller than the max?

**Comment by rjsparks** [comment]
Thats what I was thinking
