### ISSUE TITLE
Internal Server Error on editing interim meeting

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#4833]
### Describe the issue

I was editing an existing SCITT interim meeting request to add additional sessions, and upon trying to save, got an internal server error at https://datatracker.ietf.org/meeting/interim/request/interim-2022-scitt-02/edit.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
I see this error, both on production and on the sandbox - it looks like something went wrong while it was saving the changes, resulting in a partial save. Technically, it created the `Session` record for each session but did not schedule it into a `TimeSlot` as it should have. That is what led to the error you're now seeing.

Can you describe what edits you tried to make that led to the error? How many sessions did you add and what dates (roughly) did you specify?

It looks like you canceled the meeting later - guessing that was in the hopes that it would clear this up to try again. That was a reasonable thing to try, but didn't work. Partly that's because of the original problem, but I think there are some bugs to be filed related to canceling the interim...

**Comment by rjsparks** [comment]
I think #4846 obviates this issue. If it recurs, reopen this or start a new issue.
