### ISSUE TITLE
Many old draft versions missing from Datatracker

### ISSUE THREAD

**Issue by SmashManiac** [ietf-tools/datatracker#4933]
### Describe the issue

This issue appears to be related to #4898.

Several versions of older drafts do not appear in the Data Tracker UI. While they appear in the timeline diagram, they do not appear in the list of versions right above it, and clicking on the timeline to open the missing versions redirects to the latest publication instead.

This is a problem because some old drafts are still widely in use, such as SFTP version 3.

Examples:

- https://datatracker.ietf.org/doc/draft-ietf-secsh-filexfer/
- https://datatracker.ietf.org/doc/rfc3696/

Note that not all Internet Drafts are affected, such as https://datatracker.ietf.org/doc/rfc8989/

Workaround: Access the draft through https://www.ietf.org/archive/id/[name]-[version].txt

![image](https://user-images.githubusercontent.com/22013850/209896134-0d0a185e-6aea-43e8-bd08-0acb257ecb2a.png)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is a long standing issue rooted in there being a lack of information needed to create DocHistory objects for the revisions in question without making up information that the DocHistory should hold out of whole cloth. Specifically, the content of any of the metadata to be shown about the document reflecting the state it was in _at the time_ (such as who the shepherd was, if there was one, and whether there was WG state and what it was, etc.)

There are _many_ older documents affected by this, and any repair would require significant manual effort, and making up history that was never really true is almost unavoidable.

**Comment by larseggert** [comment]
Can we detect these cases and add an alert to the page?

**Comment by rjsparks** [comment]
Yes, but it will cost time to do the computation - is it worth the extra lag?
(The computation is to check that there's a DocHistory record matching each NewRevisionDocEvent. There's a loop already that may be doing most of it where the `revisions` variable is assembled.)

**Comment by rjsparks** [comment]
This particular draft is annoying enough people (curious to know why now?) that an effort, preferably coordinated by the right AD,  to synthesize appropriate DocHistory records may be worth it.

**Comment by rjsparks** [comment]
Per discussion at the tools team meeting, we will be continuing to investigate what we can do here without making up history. It may be that the fix will come with a general rework of the main document view at /doc/draft-.... to provide access to versions where the raw text exists but make it clear that there is no historical metadata available for that version.

**Comment by j-schoeff** [comment]
I was unable to get back to https://github.com/ietf-tools/datatracker/issues/4936 in time, but i want to make sure its clear that the links in that issue and mentioned here (https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02) used to work not too long ago. We have a handful of docs that reference this link because it is the most widely supported SFTP spec and they are all broken. I created the bug issue when we first noticed, it is unclear how long ago this was changed, but it is not decades or even years, a more recent change broke this.

**Comment by ewxrjk** [comment]
If its copy of draft-ietf-secsh-filexfer-02 has been deleted then perhaps it could at least stop returning draft-ietf-secsh-filexfer-13 instead, when asked for -02 (as described in #5518). The current behavior is actively misleading.

> This particular draft is annoying enough people (curious to know why now?) 

Why now: because it only just broke. It was working fine in October 2022.
- https://web.archive.org/web/20221007230001/https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02
- https://web.archive.org/web/20230104084838/https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02

**Comment by rjsparks** [comment]
Yes, and there are (as touched lightly on above) several courses of action we can take, _all_ of which have trade-offs.

The main doc page behavior is not different as far as I can reconstruct (or find in the wayback machine). If I'm right, here this became problematic is in the re-implementation of the /doc/html views. If we focused _there_ and allowed those views to point to versions of drafts we have, but don't have the metadata for, would the majority of the irritation the change is causing be alleviated?

**Comment by ewxrjk** [comment]
I couldn't say what the biggest source of trouble for anyone else is. Still, I note that the [SFTP draft links in Wikipedia](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol#History_and_development) are currently broken too, so I think the #5518 variant of the issue is practical issue for more than just me.

(It's a shame that SFTP is specified only in expired drafts; but we're not going to solve that here.)

**Comment by rjsparks** [comment]
I mined the code deeply, and the main document page has _never_ returned anything but a redirect to version 13 for version 12 of this document. What changed is the behavior of the htmlized view at /doc/html/ behavior for documents missing DocHistory. I think we should work towards a fix to _that_, cleaning the places in the new htmlization views that care about the metadata of the version being asked for.

**Comment by ewxrjk** [comment]
I'm not entirely clear what's been changed - https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02 still returns the -13 version for instance.

**Comment by rjsparks** [comment]
A PR has been merged to main, but not yet released to production. I expect that release to happen towards the end of this week.

**Comment by ewxrjk** [comment]
That looks right now!
