### ISSUE TITLE
sidebar: If selecting an older version, the defaults for the diff are wrong

### ISSUE THREAD

**Issue by paulwouters** [ietf-tools/datatracker#4972]
### Describe the issue

If there are 03 versions of a draft, and in the sidebar I select version 02, it displays this properly but still leaves the default "diff between versions" for the diff between 02 and 03, instead of the diff between 02 and 01.

eg my workflow:
1) select latest version. click side by side diff.
2) select previsuous version, click on side by side diff (oops it is the same diff as 1)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Hi @paulwouters - while we are all focused on /doc/html at the moment, we know what you mean, but it would be very helpful for future issues in case they develop any age before they are addressed for you to be explicit about what URLs you are looking at rather than saying something like "sidebar" (of which there are _many_ throughout the datatracker).
A fast way to do that is to just paste in an example of what's in the URL bar when you are seeing the thing you are reporting.

**Comment by paulwouters** [comment]
Will doSent using a virtual keyboard on a phoneOn Jan 11, 2023, at 14:49, Robert Sparks ***@***.***> wrote:﻿
Hi @paulwouters - while we are all focused on /doc/html at the moment, we know what you mean, but it would be very helpful for future issues in case they develop any age before they are addressed for you to be explicit about what URLs you are looking at rather than saying something like "sidebar" (of which there are many throughout the datatracker).
A fast way to do that is to just paste in an example of what's in the URL bar when you are seeing the thing you are reporting.
