### ISSUE TITLE
IETF 115 plenary bluesheet is for the welcome reception

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#5001]
### Describe the issue

The bluesheet listed for the IETF Plenary on the IETF-115 proceedings is actually for the welcome reception. The file begins:
```
Bluesheet for IETF-115: ietf Welcome Reception Sun-1700
========================================================================

292 attendees.

```
Looking at the data, there is no bluesheet associated with the plenary session:
```
>>> from ietf.meeting.models import *
>>> m = Meeting.objects.get(number='115')
>>> m.session_set.filter(type='plenary').first().bluesheets()
[]
```
but there is one for the welcome reception:
```
>>> m.session_set.filter(name='Welcome Reception').first().bluesheets()
[<Document: bluesheets-115-ietf-202211061700>]
```
This is shown for the plenary because both sessions belong to the "ietf" group - see #4928. When that bug is fixed, no bluesheets will appear for the plenary.

A bluesheet will need to be manually added to the IETF plenary session.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
That bluesheet (labelled internally to say "Welcome Reception" is _actually_ the bluesheet for the Plenary.
This is a known issue with the current api that Meetecho uses, where we use `item` to distinguish multiple meetings of a group, and ordering is inconsistently computed for groups like `ietf`. We will eventually improve that API. In the meantime, I'll ask the secretariat to cut a new version of the bluesheet with the correct label, leaving it attached to the session it's currently attached to. After the upcoming improvements to the proceedings land, if that turns out to not be the correct session, we can re-attach it.

**Comment by jennifer-richards** [comment]
I believe this is fixed
