### ISSUE TITLE
Profile page Active Drafts sections need improved filters for drafts that have become RFCs

### ISSUE THREAD

**Issue by jennybui1** [ietf-tools/datatracker#5194]
### Describe the issue

Hi, 

We received a ticket that on this person record (https://datatracker.ietf.org/person/ludwig@clemm.org) it lists a nonactive wg ([draft-clemm-nmrg-dist-intent](https://datatracker.ietf.org/doc/draft-clemm-nmrg-dist-intent/)) as Active. 

Ticket: https://rt5.ietf.org/Ticket/Display.html?id=14903

Jenny 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
The problem is here:

https://github.com/ietf-tools/datatracker/blob/main/ietf/person/models.py#L188-L190

There is more than one state machine with "active" as a state. In the case reported above, the RG state machine is still in the "active" state.

The query above should be modified to match only the 'draft' state machine.

Similar adjustments should be made to the queries around it.
