### ISSUE TITLE
Action Holder is empty when draft is in IESG State "Publication Requested"

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-tools/datatracker#5227]
### Describe the issue

First off, thank you so much for the Action Holder feature, it's amazing. I think I might have found a bug in it though. When a WG chair requests publication on a document, the Action Holder field appears but it starts off empty. Would it be possible to have it start filled in with the name from the "Responsible AD" field instead? I noticed a [draft](https://datatracker.ietf.org/doc/draft-ietf-babel-mac-relaxed/) stuck in this state and a few of us were confused as we didn't know who to ask.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment]
I just tried this in my dev instance and I cannot reproduce. When I pub-request a doc, the responsible AD becomes the action holder.

**Comment by rjsparks** [comment]
@DavidSchinazi to help with diagnostics which document did you notice this on?

Fwiw, I can reproduce this using an EDM document in a dev instance (IAB program instead of WG) - after pubreq:
![image](https://user-images.githubusercontent.com/10996692/221915670-eb7945f2-8ad2-49e9-bb18-9de21ab77282.png)

**Comment by rjsparks** [comment]
I can reproduce this with a WG document as well.

**Comment by DavidSchinazi** [comment]
draft-ietf-babel-mac-relaxed
