### ISSUE TITLE
Interim WG Meeting request "series" with "add session" does not work

### ISSUE THREAD

**Issue by ietf-secretariat** [ietf-tools/datatracker#5468]
### Describe the issue

We got a report from a WG Chair (Barry Leiba) that when he attempted to add a series of interim meetings the tool would not let him add a second session, so he added each meeting instance to the datatracker separately. I (Amy Vezza) tried to mock add a series of interims for a random WG and the add session button did not work for me either. 

Thank you!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
What does it mean to have a second session in a series of interim meetings? That each day in the series there would be two sessions?

**Comment by akvezza** [comment]
No. As the tool states "Use Series for a series of separate meetings, such as periodic interim calls."  From here: 
https://datatracker.ietf.org/meeting/interim/request 
if you choose "meeting type" as "series," fill in all the bits and pieces, and choose the "+ add session" button at the bottom, it should pop up with another session request so you can add the second interim meeting in the series - so for WGs like CBOR or CORE that do regular biweekly interims, it gives them a way to add them all - and this is conjecture - but I think the intent was to announce them with one announcement instead of six all at the same time. The most recent guidance for interim meetings has this as a bullet point:

"Recurring meetings may be scheduled together, with a single announcement." 

However, it is ENTIRELY possible this sentence is a remnant from when interim meeting announcements were hand-crafted by the Secretariat when such a thing was normal, but holding a series of interim meetings was somewhat rare. The datatracker, with needing to create a space for meeting materials for each meeting and especially the integration with Meetecho makes announcing a series of six in one email a bit more complicated, maybe.
