### ISSUE TITLE
Draft submission fails validation if title is split across lines at a hyphen in text format

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#5691]
### Describe the issue

I try to upload this draft, which has worked in the past. Now, I get a confusing screen that, if I read to the bottom, indicates that the draft was rejected because the title is too long. The error reads:
```
Submission rejected: Text Internet-Draft title (Unilateral Opportunistic Deployment of Encrypted Recursive-to- Authoritative DNS) disagrees with XML Internet-Draft title (Unilateral Opportunistic Deployment of Encrypted Recursive-to-Authoritative DNS)
```

GitHub is not allowing me to attach the XML file that causes this error. The relevant bit is:
```
<rfc ipr="trust200902" docName="draft-ietf-dprive-unilateral-probing-06" category="std" consensus="true" submissionType="IETF">
  <front>
    <title abbrev="Unilateral Encrypted Authoritative DNS">Unilateral Opportunistic Deployment of Encrypted Recursive-to-Authoritative DNS</title>
 ```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment]
The problem is not that the title is too long, it's that it is split across lines in the text rendering at a hyphen. The lines are then incorrectly joined with a space, causing the validator to believe that the text version has a different title than the XML version.

This check may have been ignored by the old submission validations when we generated our own text from an XML-only upload, but the code path is now shared between that case and the case when a user uploads both XML and their own text.

We can fix this by skipping the check when we generated our own text and/or by properly joining multiline titles when lines end in hyphens. Probably the latter is preferable because it avoids hiding a bug in the text file parsing.

**Comment by paulehoffman** [comment]
"Skipping the check" is probably more reliable. There are reasons that a line might end in a hyphen that is not a hyphenated word, as as at the "Pre-" in  "An Examination of the Obscure Security Properties of Pre- and Post-Colonial Protocols"

**Comment by jennifer-richards** [comment]
That's true - I don't think we're going to get a perfect parser going. For now, I think the more common case is the one that caused the failure here so it is better to get that right. I'll create a ticket to improve the handling of title validation.

I will also create one to improve the UI experience on the status page when the validation of a draft fails. It's definitely confusing (or worse) now.

**Comment by paulehoffman** [comment]
Thanks! Yeah, I had to read the page twice before I could figure out why it said that the XML I submitted had no title and was zero length.

**Comment by cabo** [comment]
When would that validation ever fail?
When xml2rfc is broken.
I don't think we should punish submitters of drafts for xml2rfc being broken.

**Comment by rjsparks** [comment]
>  I don't think we should punish submitters of drafts for xml2rfc being broken.

I agree with

>When would that validation ever fail?
>When xml2rfc is broken.

That's not the only way it can be made to fail as this very issue points out. The validating code is at fault.

We will change the code path back to where this is not blocking when only xml is submitted, but in the long run we need to review the checks and move any that are showing up problems actually in the xml to the xml tests.
