### ISSUE TITLE
The NomCom chair is not eligible for NomCom

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/datatracker#5943]
### Describe the issue

I had to remove myself manually after I had volunteered during meeting registration prior to being appointed.

(Rich failed to notice that he was on the list at first.  I only noticed because of that problem, so I made a point of give the list a once-over.)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Agreed that this is something the datatracker should take care of since it knows who the nomcom chairs are.

But, be aware that there are several ways that someone can be disqualified that the datatracker _doesn't_ know about. (such as being a contractor to the LLC, or officers of organizations that the RFC calls out that we do not model in the datatracker).

**Comment by martinthomson** [comment]
Good points.  I think that in a lot of those cases, the people involved will not volunteer.  Or at least it would be less common.
