### ISSUE TITLE
Tutorials end in 2021

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/datatracker#6473]
### Describe the issue

https://datatracker.ietf.org/group/edu/materials/ is linked from the "Other" menu under "Tutorials". The EDU team ended in 2021, and so does the list of materials.

@ghwood where are we capturing these tutorials now, so we can update the link?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
And IIRC the plan was to move the edu materials back out of the datatracker?

**Comment by rjsparks** [comment]
To be clear - recent and planned future materials end up attached to sessions instead of being freestanding. The attempt to use the datatracker to hold edu assets that weren't ostensibly meeting specific didn't work out - in reality they really are better modeled as meeting specific things. So there's this collection of history here that, the last time we talked about it, was going to move off into a wiki again. Removing the menu item is the right thing to do (but @ghwood should weigh in).

**Comment by ghwood** [comment]
Removing the menu/tab item is fine but there may yet be some materials that don't exist elsewhere but which should be retained. I am double checking with eodir co-coordinators (one is out until the end of October, I think). It would be nice to retain access to the materials in datatracker until we're able to convene.
