### ISSUE TITLE
Youtube link is not shown in Notes and Recordings section of past meeting materials

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6543]
See https://datatracker.ietf.org/meeting/interim-2023-tools-11/session/tools

There is an icon in the top right that links to the youtube recording.

There should also be a row for it in the Notes and Recordings section of that view.

**Comment by richsalz** [comment]
I think this line is wrong:
```
{% if meeting.number|add:"0" >= 80 %}
```

When I change it to ```{% if 1 %}``` I see the desired links.

**Comment by rjsparks** [comment]
`{% if 1 %}` is always True. - it would show links that would not work for, e.g., IETF79.

btw - a permalink into the repo would be better than a cut-paste of a single line.

**Comment by richsalz** [comment]
Thanks for the tip, will try to remember to do that.  My point was that the [current if test](https://github.com/ietf-tools/datatracker/blob/3bfb9303bca2cc4cb2e0a570f65204ac01087829/ietf/templates/meeting/session_details_panel.html#L323)  seems to be always failing.  And it turns out because it thinks the meeting from your example is `interim-2023-tools-11`

**Comment by rjsparks** [comment]
_that_'s awesome.

Yes, the conditional will have to become aware of meeting type.

**Comment by rjsparks** [comment]
(sorry - manage to get the wrong button)
