### ISSUE TITLE
dt-rfc Draft files not found

### ISSUE THREAD

**Issue by becarpenter** [ietf-tools/datatracker#6674]
### Describe the issue

https://dt-rfc.dev.ietf.org/doc/draft-ietf-anima-grasp/15/ only shows 

Formats [bibtext] [bibxml]

but no versions of the draft itself, and at the bottom I see `Error; cannot read 'draft-ietf-anima-grasp-15.txt'`

I was not logged in.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by auerswal** [comment]
I see a similar issue for different drafts:

I have searched for RFC 8792 on the https://dt-rfc.dev.ietf.org/ start page (not logged in), found that RFC (and the text is shown on the bottom of the page), but every draft I click on in the timeline results in a page for that draft that does not find the draft text. Instead of the draft text, the error message for the respective draft version is shown, e.g.:

```
Error; cannot read 'draft-ietf-netmod-artwork-folding-12.txt'
```
```
Error; cannot read 'draft-ietf-netmod-artwork-folding-11.txt'
```

**Comment by rjsparks** [comment]
This is a development instance and may not have the full archive synced at all times (it gets rebuilt daily).
Focus on more recent drafts for the moment please.

**Comment by rjsparks** [comment]
To be clear, we _intend_ the full archive to be present in this instance and will be tuning so that you are less likely to see missing document issues. The repository ("active" drafts) is there - you can find some quickly with https://dt-main.dev.ietf.org/doc/recent

**Comment by rjsparks** [comment]
We've made a config change so that the archive should remain in sync at this dev instance now.

**Comment by becarpenter** [comment]
Thank you!
