### ISSUE TITLE
On page `https://datatracker.ietf.org/wg/tls/about/`, link and anchor-tile to RFC spec for TLS protocol v1.2 pointing to wrong RFC (Typo) 

### ISSUE THREAD

**Issue by ppyrzanowski** [ietf-tools/datatracker#7028]
### Describe the issue

On page [https://datatracker.ietf.org/wg/tls/about/](https://datatracker.ietf.org/wg/tls/about/), the link and RFC number to the specification that describes the ***TLS protocol v1.2*** contains a typo pointing to the wrong RFC. 

Currently, the paragraph block below heading **"Charter for Working Group"** hold this link [**[RFC5346](https://datatracker.ietf.org/doc/rfc5346/)**] for TLS v1.2, when following this link i am presented a RFC spec with the Tiltle: "Operational Requirements for ENUM-Based Softswitch Use" and the working-group "([enum WG](https://datatracker.ietf.org/wg/enum/about/))". This was not the spec I was looking for.

After googling, I found the correct RFC I was looking for, is [**[rfc5246](https://datatracker.ietf.org/doc/rfc5246/)**]. I quickly noticed the slipup, [5***3***46] ⇾ [5***2***46].

Let me know if I'm allowed to contribute, I'm happy to fix this issue and propose a pull request.

FYI: The RFC number and link for TLS v1.3 is correct, I did not check the other ones.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Thanks Patrik -

The issue you report is with charter text. Changing that in the past has involved the IESG going through the full recharter process. There's a lighter process that the IESG has discussed for simple markup changes, but since this changes the _content_ of the charter (even if it's just to correct a typo), I'm not sure we can use it. (It also isn't fully developed in the tooling).

I'll make sure the responsible AD is aware of the typo and discuss with him how to address it.

**Comment by rjsparks** [comment]
Closing this as OBE (the charter text has been adjusted).
