### ISSUE TITLE
Error uploading draft-deng-spring-sr-loop-free

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7454]
### Describe the issue

From: 	"LiJie Deng" <denglijie1020@gmail.com>
Subject: 	An error about uploading a manuscript

Hello,
I have a question to ask you about uploading a manuscript. After uploading draft-deng-spring-sr-loop-free-02, the page cannot display the txt format of the manuscript and reports an error: "Error: cannot read 'draft-deng-spring-sr- loop-free-02.txt'".
How to solve this problem?
Looking forward to your reply.
https://datatracker.ietf.org/doc/draft-deng-spring-sr-loop-free/02/

Best regard,
Lijie Deng
![417857](https://github.com/ietf-tools/datatracker/assets/22178783/fe56d1f8-ddee-4ab9-acb3-2ef14ee4d6b8)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
Note the gap between submission and approval on the history page:

![image](https://github.com/ietf-tools/datatracker/assets/10996692/12d3fb97-e677-487f-a460-03bf1f142217)

That's approximately 60 days. Since earlier this year, the staging directory holding unconfirmed submissions is cleared after 14 days. The approval above should not have succeeded - the files that were uploaded in March are long gone.

We'll adjust the submission approval step to note that the submission has timed out.

To recover, we can either 
* change the datatracker to revert its idea of the current revision to -01. We would leave notes in the history explaining what happened. This would allow a new submission of -02

or

*  leave it with -02 missing. Leave a note in the history explaining what happened. Then the authors could submit -03.

**Comment by cindymorgan** [comment]
I checked with the author, and they'd like to revert the current revision back to -01 and then resubmit -02.

**Comment by rjsparks** [comment]
This is addressed - see the [history of the draft](https://datatracker.ietf.org/doc/draft-deng-spring-sr-loop-free/history/). I removed more history than I intended (I hand planned to leave the record of the submitted and approved draft 60 days apart), but that's not what we ended up with.
