### ISSUE TITLE
Menus mistakenly look complete when actually further content can be scrolled to

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/datatracker#7528]
### Describe the issue

Selecting the Group menu and then hovering over Security shows a menu as per the attached screenshot.  This menu only shows some of the groups and can be scrolled to see more but due to two factors, most people will look at that and think this is the complete list of groups.  Those two factors are a) that the menu does not extend down as far as it can given the window size; and b) it does not display a scrollbar or some form of 'more below' indicator.

Recommend that the scrollbar is forced to display when an incomplete list is shown, or the bottom line of the menu has a down arrow or some other indicator that there are further entries below.

![Screenshot 2024-06-13 at 10 32 31](https://github.com/ietf-tools/datatracker/assets/80711/61da65d1-e834-4977-9916-488c3bc7b4c4)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This has improved with the recent changes to the way the scroll bars in the menu items work, but the scroll bars can disappear when there's no cursor motion for some time. @holloway - can they be forced to remain on?

**Comment by holloway** [comment]
@rjsparks unfortunately not, that's an operating system UI rendering issue, mostly on [OSX](https://i.imgur.com/ShYCYx9.jpeg) and touch devices. There are CSS properties for `overflow: scroll` but they're more about whether the user _can_ scroll, not how the scrollbar is rendered.
There are UX patterns to indicate more scrolling... historically some people fake their own scrollbars in JS (which never looks great/native, although performance can be nearly identical), but the contempory solution usually involves [JS to dynamically set drop shadows and other indicators inside the scrolling area](https://stevebauman.ca/adding-scroll-shadows-to-overflow-containers/) to enhance the native scrollbar rendering rather than replace it.

**Comment by JayDaley** [comment]
I'm happy with any visual indicator.

**Comment by holloway** [comment]
This has now been deployed to prod.
