### ISSUE TITLE
Try to combine the /slides and /propose-slides endpoints in meeting material management.

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#7705]
Right now, it is confusing what link a chair should send to their presenters when encouraging them to upload slides. The chair sees /slides, but the presenters have to use /propose-slides.

It might be better to use a single endpoint (/slides) and make the endpoint behave differently (being very transparent about what's happening) given the role of the person using it.

RjS

**Comment by kivinen2** [comment]
The current url has session number in it, which makes it also more difficult for the chair to send it out, as he always needs to go and find the session number for next meeting:

http://localhost:8000/meeting/120/session/33058/slides
http://localhost:8000/meeting/120/session/33058/propose_slides

Btw, the propose_slides page do work for the chair, there is just no link for it anywhere, meaning fixing #7178 could be very simple, just add link to propose_slides page in meeting materials page. This would also allow chairs to pick that instead of the upload slides when they are asking people to send slides.
