### ISSUE TITLE
Datatracker menu covers draft name in Chrome

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7920]
### Describe the issue

Reported by Lixia Zhang:

```
To: 	support@ietf.org
Date: 	Mon, 9 Sep 2024 05:05:26 -0700
Subject: 	issue with viewing ietf documents
From: 	"Lixia Zhang" <lixia@cs.ucla.edu>

please see the screen capture below: the data tracker on the top of the page partially blocks the internet-draft title
(this has been a persistent problem)

browser: chrome

thanks, Lixia
```

[Screenshot 2024-09-10 at 8.36.23 AM.png.pdf](https://github.com/user-attachments/files/16955891/Screenshot.2024-09-10.at.8.36.23.AM.png.pdf)

Note from Cindy: I wasn't able to replicate this using Chrome Version 128.0.6613.120 on MacOS 11.1

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cindymorgan** [comment]
Lixia is using:

Chrome: Version 128.0.6613.120 (Official Build) (arm64)
OS: macOS 14.6.1

**Comment by jennifer-richards** [comment]
I'm not seeing it here with chrome (or firefox) - the menus that are causing the overlap fold away into a button widget instead of wrapping when I narrow my browser (screenshot below). This works correctly for me even if I change font sizes.

Chrome: Version 128.0.6613.114 (Official Build) (arm64) 
OS: macOS 14.6.1

<img width="947" alt="image" src="https://github.com/user-attachments/assets/c8c150ab-56a7-4bb2-8b21-b2929352f66d">
